#!/usr/bin/env bash

# habitat-plant

# environment setup
seeds/env

# package management
seeds/homebrew

# utilities
seeds/wget
seeds/tree

# git
seeds/git
seeds/git-config

# editors
seeds/vim
seeds/atom

exit 0
