#!/usr/bin/env bash

# fonts

(ls ~/Library/Fonts/** | grep "Inconsolata") && exit 0

echo "Go download SkyFonts to sync desktop fonts with Google, Monotype, Linotype, ITC, Bitstream and more" >&2

open "http://www.fonts.com/browse/font-tools/skyfonts"

echo "Makes sure to get Inconsolata. It's the best." >&2
