#!/usr/bin/env bash

# git-config

require env

source ~/.env

gitconfig_file=$HABITAT_ROOT/climates/.gitconfig
gitconfig_example=$gitconfig_file.example

test -L ~/.gitconfig \
  && test "$(git config --global --get user.name)" = "$NAME" \
  && test "$(git config --global --get user.email)" = "$EMAIL" \
  && exit 0

echo "Making $gitconfig_file from $gitconfig_example"
cp $gitconfig_example $gitconfig_file

echo "Creating symlink to $gitconfig_file in $HOME"
ln -sf $gitconfig_file $HOME

git config --global user.name "$NAME"
git config --global user.email "$EMAIL"
