#!/usr/bin/env bash

# mongodb-data-dir

require mongodb

# The mongodb daemon expects a data directory at
# /data/db
#
# See mongodb installation page for details
datadir=/data/db

test -d $datadir || {
  sudo -v
  sudo mkdir -p $datadir
  sudo chmod +rw $datadir
}
