#!/usr/bin/env bash

# osx-time-machine
#
# Time Machine
# attribution/inspiration: https://mths.be/osx

# Ask for the administrator password upfront
sudo -v

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable local Time Machine backups
hash tmutil &> /dev/null && sudo tmutil disablelocal
