#!/usr/bin/env bash

# osx-disk-utility
#
# Disk Utility
# attribution/inspiration: https://mths.be/osx

# Ask for the administrator password upfront
sudo -v

# Enable the debug menu in Disk Utility
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true
defaults write com.apple.DiskUtility advanced-image-options -bool true
