#!/usr/bin/env bash

# osx-terminal
#
# attribution/inspiration: https://mths.be/osx

require fonts

# Use a modified version of the Solarized Dark theme by default in Terminal.app
TERM_PROFILE='Solarized Dark'
CURRENT_PROFILE="$(defaults read com.apple.terminal 'Default Window Settings')"

[ "$CURRENT_PROFILE" = "$TERM_PROFILE" ] && exit 0

open "$HABITAT_ROOT/climates/Solarized Dark.terminal"
sleep 1 # Wait a bit to make sure the theme is loaded

echo "Open Terminal settings and set the Default and Startup profiles to Solarized Dark" >&2
