#!/usr/bin/env bash

# postgresql

require homebrew

brew-exists postgresql && exit 0

brew install postgresql

# To have launchd start postgresql at login:
ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents

# Then to load postgresql now:
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

echo "Make sure to create your main database: 'createdb $USER'" >&2
