#!/usr/bin/env bash

# ruby

require ruby-install

ruby_install_dir="$HOME/.rubies"
ruby_versions="2.2.0 2.3.1"

for ruby_version in $ruby_versions; do
  ruby-exists $ruby_version || {
    ruby-install ruby --rubies-dir $ruby_install_dir $ruby_version
  }
done

symlink-exists .gemrc || symlink-to-home .gemrc
symlink-exists .railsrc || symlink-to-home .railsrc
