#!/usr/bin/env bash

# ruby

require ruby-install

ruby_versions="1.9.3-p547 2.0.0-p576 2.1.2 2.1.3"

for ruby_version in $ruby_versions; do
  ruby-exists $ruby_version || {
    ruby-install ruby $ruby_version
  }
done
