#!/usr/bin/env bash

# shell-profile

require env

for file in .bash_options \
            .bash_paths \
            .bash_config \
            .bash_aliases \
            .bash_completion \
            .bash_prompt \
            .bash_profile \
            .bashrc; do
              symlink-exists $file || symlink-to-home $file
            done

source ~/.bash_profile
