#!/usr/bin/env bash

# shell-completion

require homebrew
require git
require bash-completion

COMPLETION=$HABITAT_ROOT/climates/.bash_completion

[ ~/.bash_completion -ef $COMPLETION ] && exit 0

ln -sf $COMPLETION $HOME
