tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/services"
cask "java" # pre-req for neo4j
brew "autoconf"
brew "autojump"
brew "bash"
brew "bash-completion"
brew "cmake"
brew "cowsay"
brew "doxygen"
brew "entr"
brew "exercism"
brew "fswatch"
brew "gist"
brew "perl"
brew "git"
brew "haskell-stack"
brew "heroku"
brew "hub"
brew "jq"
brew "openssl"
brew "libevent"
brew "libffi"
brew "libyaml"
brew "makedepend"
brew "mongodb", restart_service: :changed
brew "neo4j", restart_service: :changed
brew "sqlite"
brew "python"
brew "postgresql", restart_service: true
brew "rbenv"
brew "redis", restart_service: :changed
brew "ruby"
brew "ruby-install"
brew "sphinx-doc"
brew "tmux"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "xz"
cask "atom"
cask "cakebrew"
cask "dropbox"
cask "keycastr"
cask "google-chrome"
cask "postico"
cask "spotify"
