#!/usr/bin/env bash

# habitat-seed

seed_name=$1

shift 1
seed_script=$@

seed_file="seeds/$seed_name"

[ -x $seed_file ] && {
  echo "$seed_file already exists"
  exit 1
}

touch $seed_file
chmod +x $seed_file

echo "#!/usr/bin/env bash

# $seed_name

$seed_script" > $seed_file

echo "Created new seed $seed_name"
exit 0
