#!/usr/bin/env bash

[ $# -eq 0 ] && {
  echo "Specify a seed to plant"
  echo "Or, to plant all the seeds, run 'habitat plant all'"
  echo
  echo "Usage:"
  echo "  habitat plant <seed>"
  exit 1
}

[ $1 == "all" ] && {
  for seed in ./seeds/*; do
    $seed
  done
  exit 0
}

SEED=$1

[ ! -x ./seeds/$SEED ] && {
  echo "Error: seed $SEED doesn't exist"
  echo "To create it, run 'habitat seed $SEED'"
  exit 1
}

# Log script output to own log file
exec ./seeds/$SEED
